In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/2022_09_10000_matches_한글버전_컬럼전처리.csv')

In [3]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', '어시', '게임 세트', '바론킬', '현상금 레벨', '챔피언',
       '데스', '드래곤킬', '퍼블어시유무', '퍼블유무', '서렌으로끝났는지', '얻은 골드', '라인', '억제기잃은수',
       '킬수', '오래 있던 라인', '연속 킬', '챔피언에게가한마법피해량', '받은마법피해량', '오브젝트스틸',
       '챔피언에게입힌물리피해량', '받은물리피해량', '스펠 1 종류', '스펠 2 종류', '다시하기',
       '레드팀 블루팀 구분 (100, 200)', '다른 챔피언에게 cc기를 건 시간', '게임 시간 (초)',
       '챔피언에게 가한 피해량', '총 데미지', 'cs 수', 'cc기를 준 총 시간(미니언 포함)', '부활 대기 죽은 시간',
       '챔피언에게 가한 고정데미지피해량', '포탑 골드 획득 갯수', '시야점수', '핑와산갯수', '와드제거수', '설치와드수',
       'win'],
      dtype='object')

In [4]:
df['게임 시간 (분)'] = round(df['게임 시간 (초)']/60,2)

In [5]:
df['분당 얻은 골드'] = round(df['얻은 골드'] / df['게임 시간 (분)'],2)
df['분당 피해량'] = round(df['챔피언에게 가한 피해량'] / df['게임 시간 (분)'],2)
df['분당 cc건시간'] = round(df['다른 챔피언에게 cc기를 건 시간'] / df['게임 시간 (분)'],2)
df['분당 CS'] = round(df['cs 수'] / df['게임 시간 (분)'],0)
df['분당 죽은시간'] = round(df['부활 대기 죽은 시간'] / df['게임 시간 (분)'],2)
df['분당 시야점수'] = round(df['시야점수'] / df['게임 시간 (분)'],2)
df['분당 킬'] = round(df['킬수'] / df['게임 시간 (분)'],2)
df['분당 어시'] = round(df['어시'] / df['게임 시간 (분)'],2)
df['분당 데스'] = round(df['데스'] / df['게임 시간 (분)'],2)

In [9]:
df

,라인,win,분당 킬,분당 어시,분당 데스,퍼블유무,퍼블어시유무,분당 얻은 골드,분당 피해량,분당 cc건시간,분당 CS,분당 죽은시간,분당 시야점수
0,TOP,True,0.54,0.11,0.22,False,False,509.12,862.20,0.98,5.0,5.65,0.36
1,JUNGLE,True,0.14,0.69,0.14,False,True,382.95,570.17,0.80,1.0,2.97,0.76
2,MIDDLE,True,0.65,0.22,0.18,False,True,501.74,1100.80,1.05,5.0,4.60,0.29
3,BOTTOM,True,0.18,0.25,0.22,False,False,336.42,382.98,0.18,4.0,4.27,0.11
4,UTILITY,True,0.04,0.87,0.04,True,False,299.93,287.65,0.65,1.0,0.76,2.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,TOP,False,0.08,0.19,0.26,False,False,274.10,440.86,0.11,4.0,9.44,0.60
99996,JUNGLE,False,0.26,0.08,0.45,False,False,393.65,551.02,0.08,2.0,12.63,0.53
99997,MIDDLE,False,0.15,0.15,0.38,False,False,313.76,575.45,0.60,5.0,8.53,0.60
99998,BOTTOM,False,0.15,0.04,0.26,False,False,321.32,377.89,0.30,4.0,6.24,0.64
99999,UTILITY,False,0.08,0.23,0.38,False,False,257.07,468.87,0.60,2.0,8.98,0.86

In [6]:
df = df.loc[:,['라인','win','분당 킬','분당 어시','분당 데스','퍼블유무','퍼블어시유무','분당 얻은 골드','분당 피해량','분당 cc건시간','분당 CS','분당 죽은시간','분당 시야점수']]

In [7]:
df = df[df['라인'] != 'Invalid']

In [8]:
df.to_csv('data/모델돌릴꺼2.csv')